<?php


/**
 * Skeleton subclass for performing query and update operations on the 'admob' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Mar 21 23:08:44 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AdmobPeer extends BaseAdmobPeer {

} // AdmobPeer
