<?php


/**
 * Skeleton subclass for performing query and update operations on the 'audio_like' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jul 15 18:04:22 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AudioLikePeer extends BaseAudioLikePeer {

} // AudioLikePeer
