<?php


/**
 * Skeleton subclass for performing query and update operations on the 'broadcast_notification' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct  7 23:25:15 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BroadcastNotificationPeer extends BaseBroadcastNotificationPeer {

} // BroadcastNotificationPeer
