<?php


/**
 * Skeleton subclass for representing a row from the 'fixed_calendar_message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jan 27 18:42:55 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FixedCalendarMessage extends BaseFixedCalendarMessage {

	/**
	 * Initializes internal state of FixedCalendarMessage object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // FixedCalendarMessage
