<?php


/**
 * Skeleton subclass for representing a row from the 'forum_user_permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 26 17:43:27 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ForumUserPermission extends BaseForumUserPermission {

	/**
	 * Initializes internal state of ForumUserPermission object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // ForumUserPermission
