<?php


/**
 * Skeleton subclass for performing query and update operations on the 'picture_uu_count' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec  4 23:28:10 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PictureUuCountPeer extends BasePictureUuCountPeer {

} // PictureUuCountPeer
