<?php


/**
 * Skeleton subclass for performing query and update operations on the 'remote_command' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep 11 17:31:35 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RemoteCommandPeer extends BaseRemoteCommandPeer {

} // RemoteCommandPeer
