<?php


/**
 * Skeleton subclass for representing a row from the 'textline_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar 27 08:00:47 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TextlineCategory extends BaseTextlineCategory {

	/**
	 * Initializes internal state of TextlineCategory object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function __toString()
	{
		if($this->getAppId() == '31000018'){
			if($this->getId() == -5){
				$name = 'Fixed' ;
			} else {
				$name = 'Normal' ;
			}
		} else {
			$name = $this->getName() ;
		}
		return $name ;
	}


} // TextlineCategory
