<?php


/**
 * Skeleton subclass for performing query and update operations on the 'textline' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar 27 08:00:47 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TextlinePeer extends BaseTextlinePeer {

	public static function doSelectWithGroup($criteria)
	{

		$user = sfContext::getInstance()->getUser() ;
		if(!$user->isSuperAdmin()){
			$groups = $user->getGroups() ;
			if(count($groups) > 0){
				foreach($groups as $group){
					$criteria->addOr(TextlinePeer::APP_ID, $group->getName());
				}
			} else {
				$criteria->addOr(TextlinePeer::APP_ID, '00000000') ;
			}
		}

		return TextlinePeer::doSelect($criteria) ;
	}

	public static function doCountWithGroup($criteria)
	{
		$user = sfContext::getInstance()->getUser() ;
		if(!$user->isSuperAdmin()){
			$groups = $user->getGroups() ;
			if(count($groups) > 0){
				foreach($groups as $group){
					$criteria->addOr(TextlinePeer::APP_ID, $group->getName());
				}
			} else {
				$criteria->addOr(TextlinePeer::APP_ID, '00000000') ;
			}
		}

		return TextlinePeer::doCount($criteria) ;
	}
} // TextlinePeer
