<?php


/**
 * Skeleton subclass for performing query and update operations on the 'youtube_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar 27 08:00:48 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class YoutubeCommentPeer extends BaseYoutubeCommentPeer {

} // YoutubeCommentPeer
