<?php

/**
 * Base class that represents a row from the 'swatch' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:10 2017
 *
 * @package    lib.model.om
 */
abstract class BaseSwatch extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SwatchPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the picture_id field.
	 * @var        int
	 */
	protected $picture_id;

	/**
	 * The value for the social_user_id field.
	 * @var        int
	 */
	protected $social_user_id;

	/**
	 * The value for the number_of_likes field.
	 * @var        int
	 */
	protected $number_of_likes;

	/**
	 * The value for the base_url field.
	 * @var        string
	 */
	protected $base_url;

	/**
	 * The value for the image1 field.
	 * @var        string
	 */
	protected $image1;

	/**
	 * The value for the image2 field.
	 * @var        string
	 */
	protected $image2;

	/**
	 * The value for the image3 field.
	 * @var        string
	 */
	protected $image3;

	/**
	 * The value for the image4 field.
	 * @var        string
	 */
	protected $image4;

	/**
	 * The value for the image5 field.
	 * @var        string
	 */
	protected $image5;

	/**
	 * The value for the thumbnail1 field.
	 * @var        string
	 */
	protected $thumbnail1;

	/**
	 * The value for the thumbnail2 field.
	 * @var        string
	 */
	protected $thumbnail2;

	/**
	 * The value for the thumbnail3 field.
	 * @var        string
	 */
	protected $thumbnail3;

	/**
	 * The value for the thumbnail4 field.
	 * @var        string
	 */
	protected $thumbnail4;

	/**
	 * The value for the thumbnail5 field.
	 * @var        string
	 */
	protected $thumbnail5;

	/**
	 * The value for the product_name field.
	 * @var        string
	 */
	protected $product_name;

	/**
	 * The value for the category field.
	 * @var        string
	 */
	protected $category;

	/**
	 * The value for the brand field.
	 * @var        string
	 */
	protected $brand;

	/**
	 * The value for the rating field.
	 * @var        int
	 */
	protected $rating;

	/**
	 * The value for the skin_tone field.
	 * @var        string
	 */
	protected $skin_tone;

	/**
	 * The value for the skin_type field.
	 * @var        string
	 */
	protected $skin_type;

	/**
	 * The value for the eye_color field.
	 * @var        string
	 */
	protected $eye_color;

	/**
	 * The value for the del_flag field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $del_flag;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SwatchPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->del_flag = 0;
	}

	/**
	 * Initializes internal state of BaseSwatch object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [picture_id] column value.
	 * 
	 * @return     int
	 */
	public function getPictureId()
	{
		return $this->picture_id;
	}

	/**
	 * Get the [social_user_id] column value.
	 * 
	 * @return     int
	 */
	public function getSocialUserId()
	{
		return $this->social_user_id;
	}

	/**
	 * Get the [number_of_likes] column value.
	 * 
	 * @return     int
	 */
	public function getNumberOfLikes()
	{
		return $this->number_of_likes;
	}

	/**
	 * Get the [base_url] column value.
	 * 
	 * @return     string
	 */
	public function getBaseUrl()
	{
		return $this->base_url;
	}

	/**
	 * Get the [image1] column value.
	 * 
	 * @return     string
	 */
	public function getImage1()
	{
		return $this->image1;
	}

	/**
	 * Get the [image2] column value.
	 * 
	 * @return     string
	 */
	public function getImage2()
	{
		return $this->image2;
	}

	/**
	 * Get the [image3] column value.
	 * 
	 * @return     string
	 */
	public function getImage3()
	{
		return $this->image3;
	}

	/**
	 * Get the [image4] column value.
	 * 
	 * @return     string
	 */
	public function getImage4()
	{
		return $this->image4;
	}

	/**
	 * Get the [image5] column value.
	 * 
	 * @return     string
	 */
	public function getImage5()
	{
		return $this->image5;
	}

	/**
	 * Get the [thumbnail1] column value.
	 * 
	 * @return     string
	 */
	public function getThumbnail1()
	{
		return $this->thumbnail1;
	}

	/**
	 * Get the [thumbnail2] column value.
	 * 
	 * @return     string
	 */
	public function getThumbnail2()
	{
		return $this->thumbnail2;
	}

	/**
	 * Get the [thumbnail3] column value.
	 * 
	 * @return     string
	 */
	public function getThumbnail3()
	{
		return $this->thumbnail3;
	}

	/**
	 * Get the [thumbnail4] column value.
	 * 
	 * @return     string
	 */
	public function getThumbnail4()
	{
		return $this->thumbnail4;
	}

	/**
	 * Get the [thumbnail5] column value.
	 * 
	 * @return     string
	 */
	public function getThumbnail5()
	{
		return $this->thumbnail5;
	}

	/**
	 * Get the [product_name] column value.
	 * 
	 * @return     string
	 */
	public function getProductName()
	{
		return $this->product_name;
	}

	/**
	 * Get the [category] column value.
	 * 
	 * @return     string
	 */
	public function getCategory()
	{
		return $this->category;
	}

	/**
	 * Get the [brand] column value.
	 * 
	 * @return     string
	 */
	public function getBrand()
	{
		return $this->brand;
	}

	/**
	 * Get the [rating] column value.
	 * 
	 * @return     int
	 */
	public function getRating()
	{
		return $this->rating;
	}

	/**
	 * Get the [skin_tone] column value.
	 * 
	 * @return     string
	 */
	public function getSkinTone()
	{
		return $this->skin_tone;
	}

	/**
	 * Get the [skin_type] column value.
	 * 
	 * @return     string
	 */
	public function getSkinType()
	{
		return $this->skin_type;
	}

	/**
	 * Get the [eye_color] column value.
	 * 
	 * @return     string
	 */
	public function getEyeColor()
	{
		return $this->eye_color;
	}

	/**
	 * Get the [del_flag] column value.
	 * 
	 * @return     int
	 */
	public function getDelFlag()
	{
		return $this->del_flag;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SwatchPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [picture_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setPictureId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->picture_id !== $v) {
			$this->picture_id = $v;
			$this->modifiedColumns[] = SwatchPeer::PICTURE_ID;
		}

		return $this;
	} // setPictureId()

	/**
	 * Set the value of [social_user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setSocialUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->social_user_id !== $v) {
			$this->social_user_id = $v;
			$this->modifiedColumns[] = SwatchPeer::SOCIAL_USER_ID;
		}

		return $this;
	} // setSocialUserId()

	/**
	 * Set the value of [number_of_likes] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setNumberOfLikes($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->number_of_likes !== $v) {
			$this->number_of_likes = $v;
			$this->modifiedColumns[] = SwatchPeer::NUMBER_OF_LIKES;
		}

		return $this;
	} // setNumberOfLikes()

	/**
	 * Set the value of [base_url] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setBaseUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->base_url !== $v) {
			$this->base_url = $v;
			$this->modifiedColumns[] = SwatchPeer::BASE_URL;
		}

		return $this;
	} // setBaseUrl()

	/**
	 * Set the value of [image1] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setImage1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image1 !== $v) {
			$this->image1 = $v;
			$this->modifiedColumns[] = SwatchPeer::IMAGE1;
		}

		return $this;
	} // setImage1()

	/**
	 * Set the value of [image2] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setImage2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image2 !== $v) {
			$this->image2 = $v;
			$this->modifiedColumns[] = SwatchPeer::IMAGE2;
		}

		return $this;
	} // setImage2()

	/**
	 * Set the value of [image3] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setImage3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image3 !== $v) {
			$this->image3 = $v;
			$this->modifiedColumns[] = SwatchPeer::IMAGE3;
		}

		return $this;
	} // setImage3()

	/**
	 * Set the value of [image4] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setImage4($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image4 !== $v) {
			$this->image4 = $v;
			$this->modifiedColumns[] = SwatchPeer::IMAGE4;
		}

		return $this;
	} // setImage4()

	/**
	 * Set the value of [image5] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setImage5($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image5 !== $v) {
			$this->image5 = $v;
			$this->modifiedColumns[] = SwatchPeer::IMAGE5;
		}

		return $this;
	} // setImage5()

	/**
	 * Set the value of [thumbnail1] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setThumbnail1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumbnail1 !== $v) {
			$this->thumbnail1 = $v;
			$this->modifiedColumns[] = SwatchPeer::THUMBNAIL1;
		}

		return $this;
	} // setThumbnail1()

	/**
	 * Set the value of [thumbnail2] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setThumbnail2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumbnail2 !== $v) {
			$this->thumbnail2 = $v;
			$this->modifiedColumns[] = SwatchPeer::THUMBNAIL2;
		}

		return $this;
	} // setThumbnail2()

	/**
	 * Set the value of [thumbnail3] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setThumbnail3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumbnail3 !== $v) {
			$this->thumbnail3 = $v;
			$this->modifiedColumns[] = SwatchPeer::THUMBNAIL3;
		}

		return $this;
	} // setThumbnail3()

	/**
	 * Set the value of [thumbnail4] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setThumbnail4($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumbnail4 !== $v) {
			$this->thumbnail4 = $v;
			$this->modifiedColumns[] = SwatchPeer::THUMBNAIL4;
		}

		return $this;
	} // setThumbnail4()

	/**
	 * Set the value of [thumbnail5] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setThumbnail5($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumbnail5 !== $v) {
			$this->thumbnail5 = $v;
			$this->modifiedColumns[] = SwatchPeer::THUMBNAIL5;
		}

		return $this;
	} // setThumbnail5()

	/**
	 * Set the value of [product_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setProductName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->product_name !== $v) {
			$this->product_name = $v;
			$this->modifiedColumns[] = SwatchPeer::PRODUCT_NAME;
		}

		return $this;
	} // setProductName()

	/**
	 * Set the value of [category] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setCategory($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->category !== $v) {
			$this->category = $v;
			$this->modifiedColumns[] = SwatchPeer::CATEGORY;
		}

		return $this;
	} // setCategory()

	/**
	 * Set the value of [brand] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setBrand($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->brand !== $v) {
			$this->brand = $v;
			$this->modifiedColumns[] = SwatchPeer::BRAND;
		}

		return $this;
	} // setBrand()

	/**
	 * Set the value of [rating] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setRating($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rating !== $v) {
			$this->rating = $v;
			$this->modifiedColumns[] = SwatchPeer::RATING;
		}

		return $this;
	} // setRating()

	/**
	 * Set the value of [skin_tone] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setSkinTone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->skin_tone !== $v) {
			$this->skin_tone = $v;
			$this->modifiedColumns[] = SwatchPeer::SKIN_TONE;
		}

		return $this;
	} // setSkinTone()

	/**
	 * Set the value of [skin_type] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setSkinType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->skin_type !== $v) {
			$this->skin_type = $v;
			$this->modifiedColumns[] = SwatchPeer::SKIN_TYPE;
		}

		return $this;
	} // setSkinType()

	/**
	 * Set the value of [eye_color] column.
	 * 
	 * @param      string $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setEyeColor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->eye_color !== $v) {
			$this->eye_color = $v;
			$this->modifiedColumns[] = SwatchPeer::EYE_COLOR;
		}

		return $this;
	} // setEyeColor()

	/**
	 * Set the value of [del_flag] column.
	 * 
	 * @param      int $v new value
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setDelFlag($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->del_flag !== $v || $this->isNew()) {
			$this->del_flag = $v;
			$this->modifiedColumns[] = SwatchPeer::DEL_FLAG;
		}

		return $this;
	} // setDelFlag()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SwatchPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Swatch The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SwatchPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->del_flag !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->picture_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->social_user_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->number_of_likes = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->base_url = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->image1 = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->image2 = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->image3 = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->image4 = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->image5 = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->thumbnail1 = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->thumbnail2 = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->thumbnail3 = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->thumbnail4 = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->thumbnail5 = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->product_name = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->category = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->brand = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->rating = ($row[$startcol + 18] !== null) ? (int) $row[$startcol + 18] : null;
			$this->skin_tone = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->skin_type = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->eye_color = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->del_flag = ($row[$startcol + 22] !== null) ? (int) $row[$startcol + 22] : null;
			$this->created_at = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->updated_at = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 25; // 25 = SwatchPeer::NUM_COLUMNS - SwatchPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Swatch object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SwatchPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SwatchPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SwatchPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSwatch:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SwatchPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSwatch:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SwatchPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSwatch:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(SwatchPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(SwatchPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSwatch:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SwatchPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SwatchPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SwatchPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SwatchPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = SwatchPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SwatchPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPictureId();
				break;
			case 2:
				return $this->getSocialUserId();
				break;
			case 3:
				return $this->getNumberOfLikes();
				break;
			case 4:
				return $this->getBaseUrl();
				break;
			case 5:
				return $this->getImage1();
				break;
			case 6:
				return $this->getImage2();
				break;
			case 7:
				return $this->getImage3();
				break;
			case 8:
				return $this->getImage4();
				break;
			case 9:
				return $this->getImage5();
				break;
			case 10:
				return $this->getThumbnail1();
				break;
			case 11:
				return $this->getThumbnail2();
				break;
			case 12:
				return $this->getThumbnail3();
				break;
			case 13:
				return $this->getThumbnail4();
				break;
			case 14:
				return $this->getThumbnail5();
				break;
			case 15:
				return $this->getProductName();
				break;
			case 16:
				return $this->getCategory();
				break;
			case 17:
				return $this->getBrand();
				break;
			case 18:
				return $this->getRating();
				break;
			case 19:
				return $this->getSkinTone();
				break;
			case 20:
				return $this->getSkinType();
				break;
			case 21:
				return $this->getEyeColor();
				break;
			case 22:
				return $this->getDelFlag();
				break;
			case 23:
				return $this->getCreatedAt();
				break;
			case 24:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SwatchPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPictureId(),
			$keys[2] => $this->getSocialUserId(),
			$keys[3] => $this->getNumberOfLikes(),
			$keys[4] => $this->getBaseUrl(),
			$keys[5] => $this->getImage1(),
			$keys[6] => $this->getImage2(),
			$keys[7] => $this->getImage3(),
			$keys[8] => $this->getImage4(),
			$keys[9] => $this->getImage5(),
			$keys[10] => $this->getThumbnail1(),
			$keys[11] => $this->getThumbnail2(),
			$keys[12] => $this->getThumbnail3(),
			$keys[13] => $this->getThumbnail4(),
			$keys[14] => $this->getThumbnail5(),
			$keys[15] => $this->getProductName(),
			$keys[16] => $this->getCategory(),
			$keys[17] => $this->getBrand(),
			$keys[18] => $this->getRating(),
			$keys[19] => $this->getSkinTone(),
			$keys[20] => $this->getSkinType(),
			$keys[21] => $this->getEyeColor(),
			$keys[22] => $this->getDelFlag(),
			$keys[23] => $this->getCreatedAt(),
			$keys[24] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SwatchPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPictureId($value);
				break;
			case 2:
				$this->setSocialUserId($value);
				break;
			case 3:
				$this->setNumberOfLikes($value);
				break;
			case 4:
				$this->setBaseUrl($value);
				break;
			case 5:
				$this->setImage1($value);
				break;
			case 6:
				$this->setImage2($value);
				break;
			case 7:
				$this->setImage3($value);
				break;
			case 8:
				$this->setImage4($value);
				break;
			case 9:
				$this->setImage5($value);
				break;
			case 10:
				$this->setThumbnail1($value);
				break;
			case 11:
				$this->setThumbnail2($value);
				break;
			case 12:
				$this->setThumbnail3($value);
				break;
			case 13:
				$this->setThumbnail4($value);
				break;
			case 14:
				$this->setThumbnail5($value);
				break;
			case 15:
				$this->setProductName($value);
				break;
			case 16:
				$this->setCategory($value);
				break;
			case 17:
				$this->setBrand($value);
				break;
			case 18:
				$this->setRating($value);
				break;
			case 19:
				$this->setSkinTone($value);
				break;
			case 20:
				$this->setSkinType($value);
				break;
			case 21:
				$this->setEyeColor($value);
				break;
			case 22:
				$this->setDelFlag($value);
				break;
			case 23:
				$this->setCreatedAt($value);
				break;
			case 24:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SwatchPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPictureId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSocialUserId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNumberOfLikes($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setBaseUrl($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setImage1($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setImage2($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setImage3($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setImage4($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setImage5($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setThumbnail1($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setThumbnail2($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setThumbnail3($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setThumbnail4($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setThumbnail5($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setProductName($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setCategory($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setBrand($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setRating($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setSkinTone($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setSkinType($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setEyeColor($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setDelFlag($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setCreatedAt($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setUpdatedAt($arr[$keys[24]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SwatchPeer::DATABASE_NAME);

		if ($this->isColumnModified(SwatchPeer::ID)) $criteria->add(SwatchPeer::ID, $this->id);
		if ($this->isColumnModified(SwatchPeer::PICTURE_ID)) $criteria->add(SwatchPeer::PICTURE_ID, $this->picture_id);
		if ($this->isColumnModified(SwatchPeer::SOCIAL_USER_ID)) $criteria->add(SwatchPeer::SOCIAL_USER_ID, $this->social_user_id);
		if ($this->isColumnModified(SwatchPeer::NUMBER_OF_LIKES)) $criteria->add(SwatchPeer::NUMBER_OF_LIKES, $this->number_of_likes);
		if ($this->isColumnModified(SwatchPeer::BASE_URL)) $criteria->add(SwatchPeer::BASE_URL, $this->base_url);
		if ($this->isColumnModified(SwatchPeer::IMAGE1)) $criteria->add(SwatchPeer::IMAGE1, $this->image1);
		if ($this->isColumnModified(SwatchPeer::IMAGE2)) $criteria->add(SwatchPeer::IMAGE2, $this->image2);
		if ($this->isColumnModified(SwatchPeer::IMAGE3)) $criteria->add(SwatchPeer::IMAGE3, $this->image3);
		if ($this->isColumnModified(SwatchPeer::IMAGE4)) $criteria->add(SwatchPeer::IMAGE4, $this->image4);
		if ($this->isColumnModified(SwatchPeer::IMAGE5)) $criteria->add(SwatchPeer::IMAGE5, $this->image5);
		if ($this->isColumnModified(SwatchPeer::THUMBNAIL1)) $criteria->add(SwatchPeer::THUMBNAIL1, $this->thumbnail1);
		if ($this->isColumnModified(SwatchPeer::THUMBNAIL2)) $criteria->add(SwatchPeer::THUMBNAIL2, $this->thumbnail2);
		if ($this->isColumnModified(SwatchPeer::THUMBNAIL3)) $criteria->add(SwatchPeer::THUMBNAIL3, $this->thumbnail3);
		if ($this->isColumnModified(SwatchPeer::THUMBNAIL4)) $criteria->add(SwatchPeer::THUMBNAIL4, $this->thumbnail4);
		if ($this->isColumnModified(SwatchPeer::THUMBNAIL5)) $criteria->add(SwatchPeer::THUMBNAIL5, $this->thumbnail5);
		if ($this->isColumnModified(SwatchPeer::PRODUCT_NAME)) $criteria->add(SwatchPeer::PRODUCT_NAME, $this->product_name);
		if ($this->isColumnModified(SwatchPeer::CATEGORY)) $criteria->add(SwatchPeer::CATEGORY, $this->category);
		if ($this->isColumnModified(SwatchPeer::BRAND)) $criteria->add(SwatchPeer::BRAND, $this->brand);
		if ($this->isColumnModified(SwatchPeer::RATING)) $criteria->add(SwatchPeer::RATING, $this->rating);
		if ($this->isColumnModified(SwatchPeer::SKIN_TONE)) $criteria->add(SwatchPeer::SKIN_TONE, $this->skin_tone);
		if ($this->isColumnModified(SwatchPeer::SKIN_TYPE)) $criteria->add(SwatchPeer::SKIN_TYPE, $this->skin_type);
		if ($this->isColumnModified(SwatchPeer::EYE_COLOR)) $criteria->add(SwatchPeer::EYE_COLOR, $this->eye_color);
		if ($this->isColumnModified(SwatchPeer::DEL_FLAG)) $criteria->add(SwatchPeer::DEL_FLAG, $this->del_flag);
		if ($this->isColumnModified(SwatchPeer::CREATED_AT)) $criteria->add(SwatchPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(SwatchPeer::UPDATED_AT)) $criteria->add(SwatchPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SwatchPeer::DATABASE_NAME);

		$criteria->add(SwatchPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Swatch (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPictureId($this->picture_id);

		$copyObj->setSocialUserId($this->social_user_id);

		$copyObj->setNumberOfLikes($this->number_of_likes);

		$copyObj->setBaseUrl($this->base_url);

		$copyObj->setImage1($this->image1);

		$copyObj->setImage2($this->image2);

		$copyObj->setImage3($this->image3);

		$copyObj->setImage4($this->image4);

		$copyObj->setImage5($this->image5);

		$copyObj->setThumbnail1($this->thumbnail1);

		$copyObj->setThumbnail2($this->thumbnail2);

		$copyObj->setThumbnail3($this->thumbnail3);

		$copyObj->setThumbnail4($this->thumbnail4);

		$copyObj->setThumbnail5($this->thumbnail5);

		$copyObj->setProductName($this->product_name);

		$copyObj->setCategory($this->category);

		$copyObj->setBrand($this->brand);

		$copyObj->setRating($this->rating);

		$copyObj->setSkinTone($this->skin_tone);

		$copyObj->setSkinType($this->skin_type);

		$copyObj->setEyeColor($this->eye_color);

		$copyObj->setDelFlag($this->del_flag);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Swatch Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SwatchPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SwatchPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSwatch:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSwatch::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSwatch
