<?php

/**
 * Base static class for performing query and update operations on the 'itunes_sales' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:07 2017
 *
 * @package    lib.model.om
 */
abstract class BaseItunesSalesPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'itunes_sales';

	/** the related Propel class for this table */
	const OM_CLASS = 'ItunesSales';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.ItunesSales';

	/** the related TableMap class for this table */
	const TM_CLASS = 'ItunesSalesTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 24;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'itunes_sales.ID';

	/** the column name for the PROVIDER field */
	const PROVIDER = 'itunes_sales.PROVIDER';

	/** the column name for the PROVIDER_COUNTRY field */
	const PROVIDER_COUNTRY = 'itunes_sales.PROVIDER_COUNTRY';

	/** the column name for the SKU field */
	const SKU = 'itunes_sales.SKU';

	/** the column name for the DEVELOPER field */
	const DEVELOPER = 'itunes_sales.DEVELOPER';

	/** the column name for the TITLE field */
	const TITLE = 'itunes_sales.TITLE';

	/** the column name for the VERSION field */
	const VERSION = 'itunes_sales.VERSION';

	/** the column name for the PRODUCT_TYPE_IDENTIFIER field */
	const PRODUCT_TYPE_IDENTIFIER = 'itunes_sales.PRODUCT_TYPE_IDENTIFIER';

	/** the column name for the UNITS field */
	const UNITS = 'itunes_sales.UNITS';

	/** the column name for the DEVELOPER_PROCEEDS field */
	const DEVELOPER_PROCEEDS = 'itunes_sales.DEVELOPER_PROCEEDS';

	/** the column name for the BEGIN_DATE field */
	const BEGIN_DATE = 'itunes_sales.BEGIN_DATE';

	/** the column name for the END_DATE field */
	const END_DATE = 'itunes_sales.END_DATE';

	/** the column name for the CUSTOMER_CURRENCY field */
	const CUSTOMER_CURRENCY = 'itunes_sales.CUSTOMER_CURRENCY';

	/** the column name for the COUNTRY_CODE field */
	const COUNTRY_CODE = 'itunes_sales.COUNTRY_CODE';

	/** the column name for the CURRENCY_OF_PROCEEDS field */
	const CURRENCY_OF_PROCEEDS = 'itunes_sales.CURRENCY_OF_PROCEEDS';

	/** the column name for the APPLE_IDENTIFIER field */
	const APPLE_IDENTIFIER = 'itunes_sales.APPLE_IDENTIFIER';

	/** the column name for the CUSTOMER_PRICE field */
	const CUSTOMER_PRICE = 'itunes_sales.CUSTOMER_PRICE';

	/** the column name for the PROMO_CODE field */
	const PROMO_CODE = 'itunes_sales.PROMO_CODE';

	/** the column name for the PARENT_IDENTIFIER field */
	const PARENT_IDENTIFIER = 'itunes_sales.PARENT_IDENTIFIER';

	/** the column name for the SUBSCRIPTION field */
	const SUBSCRIPTION = 'itunes_sales.SUBSCRIPTION';

	/** the column name for the PERIOD field */
	const PERIOD = 'itunes_sales.PERIOD';

	/** the column name for the DEL_FLG field */
	const DEL_FLG = 'itunes_sales.DEL_FLG';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'itunes_sales.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'itunes_sales.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of ItunesSales objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array ItunesSales[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Provider', 'ProviderCountry', 'Sku', 'Developer', 'Title', 'Version', 'ProductTypeIdentifier', 'Units', 'DeveloperProceeds', 'BeginDate', 'EndDate', 'CustomerCurrency', 'CountryCode', 'CurrencyOfProceeds', 'AppleIdentifier', 'CustomerPrice', 'PromoCode', 'ParentIdentifier', 'Subscription', 'Period', 'DelFlg', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'provider', 'providerCountry', 'sku', 'developer', 'title', 'version', 'productTypeIdentifier', 'units', 'developerProceeds', 'beginDate', 'endDate', 'customerCurrency', 'countryCode', 'currencyOfProceeds', 'appleIdentifier', 'customerPrice', 'promoCode', 'parentIdentifier', 'subscription', 'period', 'delFlg', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::PROVIDER, self::PROVIDER_COUNTRY, self::SKU, self::DEVELOPER, self::TITLE, self::VERSION, self::PRODUCT_TYPE_IDENTIFIER, self::UNITS, self::DEVELOPER_PROCEEDS, self::BEGIN_DATE, self::END_DATE, self::CUSTOMER_CURRENCY, self::COUNTRY_CODE, self::CURRENCY_OF_PROCEEDS, self::APPLE_IDENTIFIER, self::CUSTOMER_PRICE, self::PROMO_CODE, self::PARENT_IDENTIFIER, self::SUBSCRIPTION, self::PERIOD, self::DEL_FLG, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'provider', 'provider_country', 'sku', 'developer', 'title', 'version', 'product_type_identifier', 'units', 'developer_proceeds', 'begin_date', 'end_date', 'customer_currency', 'country_code', 'currency_of_proceeds', 'apple_identifier', 'customer_price', 'promo_code', 'parent_identifier', 'subscription', 'period', 'del_flg', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Provider' => 1, 'ProviderCountry' => 2, 'Sku' => 3, 'Developer' => 4, 'Title' => 5, 'Version' => 6, 'ProductTypeIdentifier' => 7, 'Units' => 8, 'DeveloperProceeds' => 9, 'BeginDate' => 10, 'EndDate' => 11, 'CustomerCurrency' => 12, 'CountryCode' => 13, 'CurrencyOfProceeds' => 14, 'AppleIdentifier' => 15, 'CustomerPrice' => 16, 'PromoCode' => 17, 'ParentIdentifier' => 18, 'Subscription' => 19, 'Period' => 20, 'DelFlg' => 21, 'CreatedAt' => 22, 'UpdatedAt' => 23, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'provider' => 1, 'providerCountry' => 2, 'sku' => 3, 'developer' => 4, 'title' => 5, 'version' => 6, 'productTypeIdentifier' => 7, 'units' => 8, 'developerProceeds' => 9, 'beginDate' => 10, 'endDate' => 11, 'customerCurrency' => 12, 'countryCode' => 13, 'currencyOfProceeds' => 14, 'appleIdentifier' => 15, 'customerPrice' => 16, 'promoCode' => 17, 'parentIdentifier' => 18, 'subscription' => 19, 'period' => 20, 'delFlg' => 21, 'createdAt' => 22, 'updatedAt' => 23, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::PROVIDER => 1, self::PROVIDER_COUNTRY => 2, self::SKU => 3, self::DEVELOPER => 4, self::TITLE => 5, self::VERSION => 6, self::PRODUCT_TYPE_IDENTIFIER => 7, self::UNITS => 8, self::DEVELOPER_PROCEEDS => 9, self::BEGIN_DATE => 10, self::END_DATE => 11, self::CUSTOMER_CURRENCY => 12, self::COUNTRY_CODE => 13, self::CURRENCY_OF_PROCEEDS => 14, self::APPLE_IDENTIFIER => 15, self::CUSTOMER_PRICE => 16, self::PROMO_CODE => 17, self::PARENT_IDENTIFIER => 18, self::SUBSCRIPTION => 19, self::PERIOD => 20, self::DEL_FLG => 21, self::CREATED_AT => 22, self::UPDATED_AT => 23, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'provider' => 1, 'provider_country' => 2, 'sku' => 3, 'developer' => 4, 'title' => 5, 'version' => 6, 'product_type_identifier' => 7, 'units' => 8, 'developer_proceeds' => 9, 'begin_date' => 10, 'end_date' => 11, 'customer_currency' => 12, 'country_code' => 13, 'currency_of_proceeds' => 14, 'apple_identifier' => 15, 'customer_price' => 16, 'promo_code' => 17, 'parent_identifier' => 18, 'subscription' => 19, 'period' => 20, 'del_flg' => 21, 'created_at' => 22, 'updated_at' => 23, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ItunesSalesPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ItunesSalesPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(ItunesSalesPeer::ID);
		$criteria->addSelectColumn(ItunesSalesPeer::PROVIDER);
		$criteria->addSelectColumn(ItunesSalesPeer::PROVIDER_COUNTRY);
		$criteria->addSelectColumn(ItunesSalesPeer::SKU);
		$criteria->addSelectColumn(ItunesSalesPeer::DEVELOPER);
		$criteria->addSelectColumn(ItunesSalesPeer::TITLE);
		$criteria->addSelectColumn(ItunesSalesPeer::VERSION);
		$criteria->addSelectColumn(ItunesSalesPeer::PRODUCT_TYPE_IDENTIFIER);
		$criteria->addSelectColumn(ItunesSalesPeer::UNITS);
		$criteria->addSelectColumn(ItunesSalesPeer::DEVELOPER_PROCEEDS);
		$criteria->addSelectColumn(ItunesSalesPeer::BEGIN_DATE);
		$criteria->addSelectColumn(ItunesSalesPeer::END_DATE);
		$criteria->addSelectColumn(ItunesSalesPeer::CUSTOMER_CURRENCY);
		$criteria->addSelectColumn(ItunesSalesPeer::COUNTRY_CODE);
		$criteria->addSelectColumn(ItunesSalesPeer::CURRENCY_OF_PROCEEDS);
		$criteria->addSelectColumn(ItunesSalesPeer::APPLE_IDENTIFIER);
		$criteria->addSelectColumn(ItunesSalesPeer::CUSTOMER_PRICE);
		$criteria->addSelectColumn(ItunesSalesPeer::PROMO_CODE);
		$criteria->addSelectColumn(ItunesSalesPeer::PARENT_IDENTIFIER);
		$criteria->addSelectColumn(ItunesSalesPeer::SUBSCRIPTION);
		$criteria->addSelectColumn(ItunesSalesPeer::PERIOD);
		$criteria->addSelectColumn(ItunesSalesPeer::DEL_FLG);
		$criteria->addSelectColumn(ItunesSalesPeer::CREATED_AT);
		$criteria->addSelectColumn(ItunesSalesPeer::UPDATED_AT);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ItunesSalesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ItunesSalesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseItunesSalesPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     ItunesSales
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ItunesSalesPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ItunesSalesPeer::populateObjects(ItunesSalesPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ItunesSalesPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseItunesSalesPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      ItunesSales $value A ItunesSales object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(ItunesSales $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A ItunesSales object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof ItunesSales) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or ItunesSales object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     ItunesSales Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to itunes_sales
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ItunesSalesPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ItunesSalesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ItunesSalesPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ItunesSalesPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseItunesSalesPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseItunesSalesPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new ItunesSalesTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? ItunesSalesPeer::CLASS_DEFAULT : ItunesSalesPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a ItunesSales or Criteria object.
	 *
	 * @param      mixed $values Criteria or ItunesSales object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseItunesSalesPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseItunesSalesPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from ItunesSales object
		}

		if ($criteria->containsKey(ItunesSalesPeer::ID) && $criteria->keyContainsValue(ItunesSalesPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ItunesSalesPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseItunesSalesPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseItunesSalesPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a ItunesSales or Criteria object.
	 *
	 * @param      mixed $values Criteria or ItunesSales object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseItunesSalesPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseItunesSalesPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ItunesSalesPeer::ID);
			$selectCriteria->add(ItunesSalesPeer::ID, $criteria->remove(ItunesSalesPeer::ID), $comparison);

		} else { // $values is ItunesSales object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseItunesSalesPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseItunesSalesPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the itunes_sales table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(ItunesSalesPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			ItunesSalesPeer::clearInstancePool();
			ItunesSalesPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a ItunesSales or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or ItunesSales object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ItunesSalesPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof ItunesSales) { // it's a model object
			// invalidate the cache for this single object
			ItunesSalesPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ItunesSalesPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				ItunesSalesPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			ItunesSalesPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given ItunesSales object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      ItunesSales $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(ItunesSales $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ItunesSalesPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ItunesSalesPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(ItunesSalesPeer::DATABASE_NAME, ItunesSalesPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     ItunesSales
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ItunesSalesPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ItunesSalesPeer::DATABASE_NAME);
		$criteria->add(ItunesSalesPeer::ID, $pk);

		$v = ItunesSalesPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ItunesSalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ItunesSalesPeer::DATABASE_NAME);
			$criteria->add(ItunesSalesPeer::ID, $pks, Criteria::IN);
			$objs = ItunesSalesPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseItunesSalesPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseItunesSalesPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseItunesSalesPeer::buildTableMap();

