	<article class="lower">
		<section id="create">

<?php if(__('LANGUAGE') == 'ja'): ?>
<p style="font-size: 1.5em;font-weight: bold;font-family: serif;">利用規約</p>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">2015年9月1日</p>
<br /><br />



<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">1.承諾について</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A. 当社のウェブサイトを利用もしくは訪問すること、当社にコンテンツを提供すること、または当社から、もしくは当社を通じて提供される当社の製品、ソフトウェア、データフィード、サービス（以下、「本サービス」と総称します）を利用することにより、お客様は、(1) 諸条件（以下、「本利用規約」といいます）および (2) 当社の一般ガイドライン（以下、「一般ガイドライン」といいます）に同意をしたとみなされます。一般ガイドラインは、次のウェブページ（<?php echo link_to('一般ガイドライン','account/guideline') ?>）を参照頂くことにより本利用規約に組み込まれます。尚、これらの条件に同意できない方は、本サービスを利用できません。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.本利用規約に対して重要な変更を行う場合、当社からお客様に通知する様に努めております。お客様は定期的に当社が提供する最新版を要請し、その内容を確認頂く必要があります。当社は、その独自の裁量に基づき、いつでも本利用規約および方針を修正または変更することができます。お客様は、それらの修正または変更がお客様に対して拘束力を有することに同意するものとします。本利用規約のいかなる定めも、何らかの権利または利益を第三者に与えないものとします。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">2. 本サービス</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.本利用規約は、本サービスのすべてのユーザー（本サービス上のコンテンツ投稿者でもあるユーザー、本サービスを有料で利用するユーザーを含みます）に対して適用するものとします。「コンテンツ」には、お客様が本サービス上で視聴し、本サービスを通じてアクセスし、または本サービスにおいて投稿するテキスト、ソフトウェア、スクリプト、画像、写真、音声、音楽、映像、オーディオビジュアル素材、インタラクティブ機能等が含まれます。本サービスには、当社のあらゆる要素（これには、当社のバンドル提供アプリケーションプログラム（以下、「バンドルプレイヤー」といいます）、当社のアップロードプログラム（以下、「アップローダー」といいます）など、当社が提供する製品、ソフトウェア、サービスの一切が含まれますが、これらに限定されません）が含まれます。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.本サービスには、第三者のウェブサイトリンク、第三者の製品、第三者のソフトウェア、または第三者のサービスであって、当社が所有または管理していないものが含まれる場合があります。当社は、第三者によるコンテンツの配信、第三者のコンテンツ、第三者のプライバシー方針、または第三者のウェブサイトの運営に関しては、いかなる管理も行っておらず、いかなる責任も負いません。さらに、当社は、第三者サイトのコンテンツの検閲または編集を行う予定はなく、それらを行うこともできません。本サービスを利用することによって、お客様は、当社による第三者ウェブサイトの使用、および第三者ウェブサイト（アプリケーションストアを含みます）上でのお客様のコンテンツの配信に起因する一切の責任について、当社を明示的に免責するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.従って、当社は、お客様が自身のコンテンツを配信する他のウェブサイトの条件およびプライバシー方針を確認することを推奨します。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">3. 当社アカウント</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.本サービスの機能へアクセスするためには、当社アカウントを開設する必要があります。許可なく他人のアカウントを使用することはできません。アカウントを開設する際は、正確かつ完全な情報を提供しなければなりません。お客様のアカウント上で発生するアクティビティについて、お客様は単独で責任を負うとともに、自身のアカウントパスワードを安全に管理しなければなりません。自身のアカウントに関してセキュリティ侵害または不正利用があったときは、ただちに当社に連絡していただく必要があります</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.当社は、お客様が自身のアカウントが不正利用されたことよって被った損失については責任を負いませんが、お客様は、その不正利用によって当社または他者が被った損失について責任を負う場合があります。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">4. 本サービスの一般的利用――許可および制限</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">当社は、お客様に対して、本利用規約の定めに従って本サービスにアクセスし、それを利用することを許可します。ただし、</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.お客様は、当社の文書による事前承認を得た場合を除き、本サービス、または本サービスにより作成されたコンテンツのいかなる部分も、いかなる媒体においても配信しないことに同意するものとします。ただし、当社が、本サービスを提供する機能を通じて（例えば、バンドルプレイヤーなど）、かかる配信のための手段を提供している場合を除きます。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.お客様は、本サービスのいずれの部分も変更・修正しないことに同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.お客様は、本サービス自体、バンドルプレイヤー、または当社が指定して明示的に承認した他の方法を用いる場合を除き、いかなる技術または方法によっても、本サービスにより作成されたコンテンツにアクセスしないことを同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">D.お客様は、当社の文書による事前承認を得ることなく、本サービスについて、以下のいずれかに該当する商業利用を行わないことに同意するものとします。(i) 本サービス、または本サービスにより作成されたコンテンツに対するアクセス権を販売すること。(ii) 本サービスまたはコンテンツ内に配置する広告、スポンサーシップ、またはプロモーションを販売すること。(iii) 広告表示を有効化したブログまたはウェブサイト上で、バンドルプレイヤーを通じて当社のビデオを表示すること。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">E.禁止対象となる商業利用には、以下のいずれかに該当するものは含まれません。(i) お客様のビジネスまたは芸術的活動を宣伝するために、当社にオリジナルビデオをアップロードすること。(ii) 当社が文書をもって明示的に承認した利用。</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">F.お客様は、当社アップローダーを利用することによって、当社アップローダーが随時に当社から自動的にアップデートのダウンロードおよびインストールを行うことに同意することになります。こうしたアップデートは、アップローダーの改善、拡張、機能追加を行うためのものであり、バグフィクス、拡張機能、新ソフトウェアモジュール、新バージョンの形態を取る場合があります。お客様は、アップローダーを利用することの一環として、そうしたアップデートを受け取ることに同意し、（当社に対して、アップデートを配信することを許可）するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">G.お客様は、ある一定の時間内において、従来型のオンラインウェブブラウザを使用することでは当該時間内に到底一人で作成できない回数のリクエストメッセージを当社のサーバーに送信する方法により、本サービスにアクセスをする自動化システム（「ロボット」、「スパイダー」、「オフラインリーダー」を含みますが、これらに限定されません）を使用または起動しないことに同意するものとします。以上の定めにかかわらず、当社は、サイトの内容に関して広く一般に利用される検索可能なインデックスを作成するという目的に限り、かつ、専らその目的に必要な範囲において、サイトの内容をコピーするためにスパイダーを使用することを、広く一般に利用される検索エンジンの運営者に対して許可します（ただし、そうした内容のキャッシュまたはアーカイブの作成は許可しません）。当社は、一般的に撤回するか個別的に撤回するかを問わず、以上の例外を撤回する権利を留保します。お客様は、本サービスを通じて、個人識別情報（アカウント名を含みます）を収集または取得しないことに同意するとともに、本サービスによって提供された通信システム（例えば、コメント、電子メール）を、商業的な勧誘を行う目的で利用しないことに同意するものとします。お客様は、ユーザーのコンテンツに関連して、商業目的の勧誘を本サービスのユーザーに対して行わないことに同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">H.お客様は、本サービスを利用するにあたって、あらゆる適用法を遵守するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">I.当社は、いつでも、本サービスのいずれかの要素を停止する権利を留保します。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">J.お客様は、本サービスに関連して当社に支払った金額について、いかなる理由であっても当社が返金しないことに同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">K.お客様は、本サービスの技術サポート、バグフィクス、拡張機能、新ソフトウェアモジュール、または本サービスの新バージョンの提供については、当社が単独の判断により決定することに同意するものとします。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">5. コンテンツの利用に対する制限等</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">上記の一般的制限に加えて、お客様がコンテンツを利用することに対して、以下の制限および条件が適用されます。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.本サービス上のコンテンツ、ならびに本サービス上の商標、サービスマークおよびロゴ（以下、「本件マーク」といいます）は、当社が所有し、または当社が許諾を受けているものであって、法律に基づく著作権およびその他の知的財産権の対象となります。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.お客様は、本サービスのセキュリティ関連機能、またはコンテンツの利用もしくはコピーを防止する機能、もしくは本サービスもしくはそのコンテンツの利用に制限をかける機能に対して、回避、無効化またはその他の方法で妨害を行わないことに同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.お客様は、本サービスの利用中、お客様が多様な情報源に由来するコンテンツに接触する可能性があることを理解するとともに、当社が、当該コンテンツの正確性、有用性、安全性または知的財産権については責任を負わないことを理解するものとします。さらに、お客様は、お客様が不正確、不快、わいせつ、またはいかがわしいコンテンツに接触する可能性があることを理解・承知するものとし、また、お客様は、それに関連してお客様が当社に対して保有し、または保有する可能性のあるコモンロー上またはエクイティ上の権利または救済措置を放棄することに同意し、ここに放棄するものとします。また、お客様は、適用法が許容する限りにおいて、お客様による本サービスの利用に関連するあらゆる事項について、法律が許容する最大限度において、当社、その所有者、運営者、関連会社、ライセンサーおよびライセンシーを補償および免責することに同意するものとします。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">6. コンテンツの提供について</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.お客様は、当社のアカウント保有者として、自身のコンテンツ（ビデオおよびユーザーコメントを含みます）を本サービスに提供することができます。「コンテンツ提供者」とは、本サービスにコンテンツを提供するユーザーのことです。お客様は、自身が提供したコンテンツに関して、当社はいかなる秘密の保持も保証しないことを理解するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.お客様は、自身のコンテンツと、本サービスに自身のコンテンツを提供および公開したことの結果について、単独で責任を負うものとします。お客様は、自身が提供するコンテンツの公開について必要なライセンス、権利、同意および許可を、所有または保有していることを確認、表明および保証するものとします。お客様は、本サービスまたは、本利用規約に従いその他のサービスを通じて公開する当該コンテンツに関する特許権、商標権、営業秘密、著作権またはその他の財産権の一切を当社に許諾するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.疑義を避けるために明記しますが、お客様は、自身のコンテンツの所有権の一切を保有し続けるものとします。ただし、当社にコンテンツを提供することによって、お客様は、当社に対して、本サービスならびに当社（ならびにその承継人および関連会社）の事業に関連して、コンテンツの利用、複製、配信、二次創作物の作成、表示、および実施（これには、あらゆる媒体形式により、かつ、あらゆる媒体チャネルを通じて、本サービスならびに／またはコンテンツ（およびその二次創作物）の一部または全体を宣伝および再配信することが含まれますが、これらに限定されません）をするための、全世界を対象とし、非独占的であり、ロイヤルティ支払義務の発生がなく、再許諾可能であり、かつ、譲渡可能なライセンスを許諾するものとします。さらに、お客様は、各エンドユーザーに対して、本サービスを通じてお客様のコンテンツにアクセスをするため、ならびに本サービスの機能および本利用規約により許容されるとおりに、コンテンツの利用、複製（バックアップの目的に限定します）、表示、およびプレイバックをするための、非独占的であり、全世界を対象とし、ロイヤルティ支払義務が発生し、または（お客様の指示によっては）発生がなく、再許諾不可能であり、かつ、譲渡不可能なライセンスを許諾するものとします。お客様が本サービスに提供したコンテンツに関して許諾した上記ライセンスは、お客様が本サービスから自身のコンテンツを除去または削除した後、当社が商業的に妥当であるとみなす期間内に終了します。ただし、お客様は、以下に掲げるものを当社が保有する場合があることについて理解し、同意するものとします。(1) 除去または削除したお客様のコンテンツのサーバーコピー、ならびに (2) 本サービスを広告または宣伝する目的で、お客様のコンテンツの抜粋を表示および配信するためのライセンス（ロイヤルティ支払義務は発生しないものとします）。お客様が提供したユーザーコメントに関してお客様が許諾した上記ライセンスは、永久に効力を有し、かつ、取消不能とします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">D.さらに、お客様は、お客様が本サービスに提供したコンテンツには、第三者の著作物または第三者のその他の財産権の対象物が含まれていないことについて同意するものとします。ただし、お客様がそれらの著作物もしくは対象物の正当な所有者から許可を得ている場合、またはその他の方法でお客様がそれらの著作物もしくは対象物を投稿する権利および本利用規約に基づき許諾されたライセンス権のすべてを当社に許諾する権利を合法的に取得している場合は除外します。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">E.さらに、お客様は、一般ガイドライン（随時に更新されることがあります）、または地方、国内および国家間における適用法規に違反するコンテンツまたはその他の内容を本サービスに提供しないことに同意するものとします。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">F.当社は、いずれかのユーザーもしくはその他のライセンサーが本サービスに提供したコンテンツ、またはコンテンツ内で表明された意見、推奨もしくは助言について、これを推薦することはありせん。当社は、コンテンツに関連するあらゆる責任を明示的に否定します。当社は、著作権を侵害する活動、および本サービスに関する知的財産権の侵害を許容しません。当社は、コンテンツが他者の知的財産権を侵害しているという連絡を適切に受けた場合、それらすべてのコンテツを除去します。当社は、事前通知をすることなくコンテンツを除去する権利を留保します。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">7.提供されたコンテンツに対する支払　</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.本利用規約に従って、当社は、本サービス上でアプリを作成し、運用されるお客様に対して、ロイヤルティを支払います。ロイヤルティの金額は、ロイヤルティ料率（以下、「ロイヤルティ料率」といいます）に、本サービスを利用してお客様がアップロードしたコンテンツに基づき受領した純収益を乗じた額とします（以下、「ロイヤルティ金額」といいます）。ロイヤルティ料率は、コンテンツ提供者と当社との間で相互に合意するものとします。当社は、相互に合意した日付までに、コンテンツ提供者にロイヤルティ金額を支払います。本第7条(A)に基づく支払のすべては、（別段の指定がない限り）日本円にて行うものとし、政府により源泉徴収が求められる場合、および適用される販売税、使用税または類似の税金がある場合は、それらの税金を控除します。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.本件利用規約で使用する「純収益」という用語は、暦月に関して、お客様のコンテンツについて当社が受領した純収益であって、お客様のコンテンツの販売または配信に関連して第三者が行う控除額、およびお客様のコンテンツに関する払戻額を差し引いた金額を意味します。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.例として、お客様のコンテンツがAndroid マーケットを通じて配信された場合、Android マーケットでは、通常、コンテンツの販売収益に対して30%の課金を行い、コンテンツの販売収益の残りの70%が当社に送金されます。当社は、収益の70%を受領後、Android マーケットを通じて販売されたコンテンツ収益の70%にロイヤルティ料率を乗じてロイヤルティ金額を計算します。算出したロイヤルティ金額は、当社がAndroid マーケットを通じて販売されたコンテンツ収益を受領した暦月の末日から30日以内お客様に対して支払われます。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">8.アカウント停止方針</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.該当する状況下において、ユーザーが違反者であると認められた場合には、当社は、ユーザーの本サービスに対するアクセスを停止し、ユーザーのコンテンツを除去します 。</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.当社は、コンテンツが 著作権侵害以外の理由（ポルノグラフィー、わいせつ性、または長さ過剰などが含まれますが、これらに限定されません）で本利用規約に違反しているかどうかを判断する権利を留保します。当社は、事前通知を送付することなく、いつでも独自の判断によって、それらのコンテンツを除去し、また、本利用規約に違反してその内容を提供したことを理由としてユーザーのアカウントを停止することができます。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">9. 保証</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">お客様は、本サービスを利用するにあたって、お客様単独の責任でこれを利用することに同意するものとします。サービスは「現状有姿」にてお客様に対して提供され、あらゆる黙示的保証（状態、商品性、特的目的への適合性、および権利侵害の不存在に関するあらゆる保証を含みますが、これらに限定されません）を含むいかなる種類の保証も適用されません。法律が許容する最大限度において、当社、その役員、取締役、従業員および代理人は、本サービスおよびお客様による本サービスの利用に関連して、明示的であるか黙示的であるかを問わず、あらゆる保証を否定します。当社は、本サイトのコンテンツまたは本サイトにリンクされたコンテンツの正確性または完全性に関して、いかなる保証も表明も行いません。当社は、以下のいずれかに該当する事項について、責任を負いません。(1) コンテンツの誤り、間違い、または不正確性。(2) 当社のサービスにお客様がアクセスしたこと、またはそれを利用したことに起因する人身傷害または財産損害（どのような性質であるかを問いません）。(3) 当社のセキュアサーバーおよび／またはそれに保存されているあらゆる個人情報および／または金銭的情報に対する不正アクセスまたはそれらの不正利用。(4) 当社のサービスへの送信または当社のサービスからの送信における中断または停止。(5) 第三者が当社のサービスから送信し、または当社のサービスを通じて送信したバグ、ウイルス、トロイの木馬またはそれらに類似するもの。(6) 本サービスを通じて投稿、電子メール送信、送信、もしくはその他の方法で提供されたコンテンツにおける誤りもしくは省略、またはそれらのコンテンツをお客様が利用したことに起因して発生したあらゆる種類の損失もしくは損害。当社は、本サービスもしくはハイパーリンクされたサービスを通じて第三者が広告もしくは売り込みを行った製品もしくはサービス、またはバナーもしくはその他の広告において紹介された製品もしくはサービスについて、いかなる保証、推薦もしくは確約も行わず、またはいかなる責任も負いません。当社は、製品またはサービスの提供者である第三者とお客様との間の取引の当事者ではなく、いかなる形においてもそれらの取引を監視する責任を負いません。あらゆる媒体を通じて、またはあらゆる環境下において、製品またはサービスを購入する場合は、お客様は、最善の判断を用いて、必要な注意を払う必要があります。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">10. 責任の制限</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">いかなる場合においても、当社、その役員、取締役、従業員または代理人は、以下のいずれかに該当する事由に起因するあらゆる直接損害、間接損害、付随損害、特別損害、懲罰的損害または結果損害について、その損害が保証、契約、不法行為、またはその他の法律理論に基づくかを問わず、当社がその損害の発生可能性について事前に通知を受けていたかを問わず、お客様に対する責任を負いません。(1) コンテンツの誤り、間違いまたは不正確性。(2) 当社のサービスにお客様がアクセスしたこと、またはそれを利用したことに起因する人身傷害または財産損害（どのような性質であるかを問いません）。(3) 当社のセキュアサーバーおよび／またはそれに保存されているあらゆる個人情報および／または金銭的情報に対する不正アクセスまたはそれらの不正利用。(4) 当社のサービスへの送信または当社のサービスからの送信における中断または停止。(5) 第三者が当社のサービスから送信し、または当社のサービスを通じて送信したバグ、ウイルス、トロイの木馬またはそれらに類似するもの。(6) 本サービスを通じて投稿、電子メール送信、送信、もしくはその他の方法で提供されたコンテンツにおける誤りもしくは省略、またはそれらのコンテンツをお客様が利用したことに起因して発生したあらゆる種類の損失もしくは損害。以上に定める責任制限は、該当する法域における法律が許容する最大限度において適用するものとします。</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">お客様は、当社が第三者のコンテンツまたは抽象的、侮辱的もしくは違法な行為には責任を負わないこと、および上記によって発生した被害または損害のリスクは、すべてお客様が負担することを明示的に確認するものとします。</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">以上の定めにかかわらず、いかなる場合であっても、当社、その役員、取締役、従業員または代理人がお客様に対して負担する責任の総額は、1米ドルを超えないものとします。</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">本サービスは、当社がアメリカ合衆国に保有する自らの施設を通じて管理および提供します。当社は、その他の場所において、本サービスが適切であること、または利用可能であることについて、いかなる表明もいたしません。その他の法域から本サービスへのアクセスまたは利用をする場合、お客様は、自らの意思によってその利用を選択するのであって、地域の法律を遵守する責任を負います。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">11. 補償</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">適用法が許容する最大限において、お客様は、以下のいずれかの事由に起因する請求、損害、義務、損失、責任、費用、債務、および経費（弁護士費用を含みますが、これに限定されません）の一切から、当社、その親会社、子会社、役員、取締役、従業員および代理人を、防御、免責および補償することに同意するものとします。(1) 本サービスの利用および本サービスに対するアクセス。(2) 本利用規約の条項に対する違反。(3) 第三者の権利（著作権、財産権またはプライバシー権を含みますが、これらに限定されません）に対する侵害。(4) お客様のコンテンツまたはお客様による本サービスの利用が、第三者に損害を生じさせたという主張。この防御および補償の義務は、本利用規約およびお客様による本サービスの利用が終了した後であっても、効力が継続します。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">12.本利用規約を受諾する能力</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">お客様は、お客様が18歳よりも年齢が上であること、もしくは（法的に）独立した未成年者であること、または法律上の親権者もしくは保護者の同意を得ていることを確認するものとします。さらに、お客様は、本利用規約に定める条項、条件、義務、確認、表明および保証について取り決めるために十分な能力および資格を有するとともに、本利用規約に従い、かつ、これを遵守するために十分な能力および資格を有することを確認するものとします。本サービスは13歳未満の子供を対象としていないため、いかなる場合であっても、お客様は、お客様が13歳以上であることを確認するものとします。お客様が13歳未満であるときは、本サービスを利用しないでください。素晴らしいサイトは他にもたくさんあります。お客様にとってどのサイトが適切であるか、ご両親に聞いてみてください。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">13.譲渡</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">お客様は、本利用規約、ならびに本利用規約に基づき許諾された権利およびライセンスを移転または譲渡することができません。ただし、当社は、無制限にそれらを譲渡することができます。</p>
<br />
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">14.一般条項</p>
<br />
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">お客様は、(1) 本サービスが東京都を拠点としていること、および (2) 本サービスは受動的なウェブサイトであって、東京都以外の法域では、当社に対して対人管轄権（個別的であるか一般的であるかを問いません）が発生しないことについて同意するものとします。本利用規約の準拠法は、東京都の実体法とします。全体であるか一部であるかを問わず、本契約に関して裁判上の紛争が生じた場合は、東京地方裁判所を第一審の専属的合意管轄裁判所とすることに合意します。本利用規約、一般ガイドラインおよび当社が本サービスに関して公表するその他の法的通知は、本サービスおよびコンテンツに関して、お客様と当社との間における完全合意を構成するものです。管轄裁判所が本利用規約のいずれかの条項を無効と判断した場合であっても、その条項が無効とされたことは、本利用規約のその他の条項の有効性には影響を与えることなく、その他の条項は完全な効力および有効性をもって存続します。本利用規約のいずれかの条項の適用を放棄した場合であっても、その条項の適用を将来においても放棄したとはみなされず、またはその他の条項の適用を放棄したとはみなされません。本利用規約に基づくいずれかの権利または条項の適用を主張しなかったとしても、その権利または条項の適用を放棄したとはみなされません。当社は、いつでも、事前通知を送付することなく、本利用規約を変更する権利を保有します。本利用規約に変更がないか確認する責任は、お客様が負担します。本利用規約について変更があった後に、本サービスを利用することにより、お客様は、変更後の本利用規約について同意し、承諾したとみなされます。お客様と当社は、本サービスに起因または関連するあらゆる訴因は、その訴因が発生してから1年以内に訴訟として提起しなければならないことに合意します。1年の期間が経過した後は、その訴因に基づく訴訟の提起は永久に禁止されます。</p>

<?php else: ?>
<p style="font-size: 1.5em;font-weight: bold;font-family: serif;">Terms of Service</p>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">Updated on May 6, 2015</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">1a.	Royalty Rate for Content Provider</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">In accordance with the Terms of Service, the Royalty Rate used herein shall be provided at the following webpage:</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;"><a href="http://veam.co/top/royaltyrateforyoutuber" style="a{color:#0000ff;}">http://veam.co/top/royaltyrateforyoutuber</a> and shall be incorporated herein by reference.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">1b.	Your Acceptance</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	By using or visiting the Veam website, providing content to Veam, or using any Veam products, software, data feeds, and services, provided to you on, from, or through Veam (collectively the "Service") you signify your agreement to (1) these terms and conditions (the "Terms of Service") and (2) Veam's general guidelines ("General Guidelines"), located at the webpage <a href="http://veam.co/top/guidelinewithback">http://veam.co/top/guideline</a> and incorporated herein by reference.  If you do not agree to any of these terms, please do not use the Service.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	Although we may attempt to notify you when major changes are made to these Terms of Service, you should periodically request and review the most up-to-date version provided by Veam.  Veam may, in its sole discretion, modify or revise these Terms of Service and policies at any time, and you agree to be bound by such modifications or revisions.  Nothing in these Terms of Service shall be deemed to confer any third-party rights or benefits.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">2. 	Service</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	These Terms of Service apply to all users of the Service, including users who are also contributors of Content on the Service and users who pay to use the Service.  "Content" includes the text, software, scripts, graphics, photos, sounds, music, videos, audiovisual combinations, interactive features and other materials you may view on, hear on, access through, or contribute to the Service.  The Service includes all aspects of Veam, including but not limited to all products, software and services offered by Veam, such as the Veam bundled application program ("Bundled Player"), the Veam upload program ("Uploader"), and other applications.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	The Service may contain third-party website links, third-party products, third-party software, or third-party services that are not owned or controlled by Veam.  Veam has no control over, and assumes no responsibility for, distribution of the Content by any third party, the content of any third party, privacy policies of any third party, or practices of any third-party website.  In addition, Veam will not and cannot censor or edit the content of any third-party site.  By using the Service, you expressly relieve Veam from any and all liability arising from Veam's use of any third-party website and from distribution of your Content on any third party website, including an application store.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.	Accordingly, we encourage you to read the terms and conditions and privacy policy of each other website that distributes your Content.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">3. 	Veam Accounts</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	In order to access some features of the Service, you will have to create a Veam account.  You may never use another's account without permission.  When creating your account, you must provide accurate and complete information.  You are solely responsible for the activity that occurs on your account, and you must keep your account password secure.  You must notify Veam immediately of any breach of security or unauthorized use of your account.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	Although Veam will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Veam or others due to such unauthorized use.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">4. 	General Use of the Service - Permissions and Restrictions</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">Veam hereby grants you permission to access and use the Service as set forth in these Terms of Service, provided that:</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	You agree not to distribute in any medium any part of the Service or the Content generated by the Service without Veam's prior written authorization, unless Veam makes available the means for such distribution through functionality offered by the Service (such as the Bundled Player).</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	You agree not to alter or modify any part of the Service.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.	You agree not to access Content generated by the Service through any technology or means other than by the Service itself, the Bundled Player, or other explicitly authorized means Veam may designate.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">D.	You agree not to use the Service for any of the following commercial uses unless you obtain Veam's prior written approval: (i) the sale of access to the Service or Content generated by the Service; (ii) the sale of advertising, sponsorships, or promotions placed on or within the Service or Content; or (iii) showing Veam videos through the Bundled Player on an ad-enabled blog or website.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">E.	Prohibited commercial uses do not include: (i) uploading an original video to Veam to promote your business or artistic enterprise; or (ii) any use that Veam expressly authorizes in writing.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">F.	If you use the Veam Uploader, you agree that it may automatically download and install updates from time to time from Veam.  These updates are designed to improve, enhance and further develop the Uploader and may take the form of bug fixes, enhanced functions, new software modules and completely new versions.  You agree to receive such updates (and permit Veam to deliver these to you) as part of your use of the Uploader.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">G.	You agree not to use or launch any automated system, including without limitation, "robots," "spiders," or "offline readers," that accesses the Service in a manner that sends more request messages to the Veam servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser.  Notwithstanding the foregoing, Veam grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials.  Veam reserves the right to revoke these exceptions either generally or in specific cases.  You agree not to collect or harvest any personally identifiable information, including account names, from the Service, nor to use the communication systems provided by the Service (e.g., comments, email) for any commercial solicitation purposes.  You agree not to solicit, for commercial purposes, any users of the Service with respect to their Content.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">H.	In your use of the Service, you will comply with all applicable laws.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">I.	Veam reserves the right to discontinue any aspect of the Service at any time.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">J.	You agree that Veam shall not provide you any refunds for any reasons of any amounts paid by you to Veam that is related to the Service.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">K.	You agree that it is in the sole discretion of Veam to provide, if at all, any technical support for the Service, any bug fixes, any enhanced functions, any new software modules, or any new versions of the Service.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">5. 	Your Use of Content</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">In addition to the general restrictions above, the following restrictions and conditions apply specifically to your use of Content.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	The Content on the Service, and the trademarks, service marks and logos ("Marks") on the Service, are owned by or licensed to Veam, subject to copyright and other intellectual property rights under the law.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	You agree not to circumvent, disable or otherwise interfere with security-related features of the Service or features that prevent or restrict use or copying of any Content or enforce limitations on use of the Service or the Content therein.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.	You understand that when using the Service, you may be exposed to Content from a variety of sources, and that Veam is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Content.  You further understand and acknowledge that you may be exposed to Content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Veam with respect thereto, and, to the extent permitted by applicable law, agree to indemnify and hold harmless Veam, its owners, operators, affiliates, licensors, and licensees to the fullest extent allowed by law regarding all matters related to your use of the Service.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">6. 	Your Content and Conduct</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	As a Veam account holder you may submit your Content to the Service, including videos and user comments.  "Content Provider" is a user that submits Content to the Service.  You understand that Veam does not guarantee any confidentiality with respect to any Content you submit.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	You shall be solely responsible for your own Content and the consequences of submitting and publishing your Content on the Service.  You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish Content you submit; and you license to Veam all patent, trademark, trade secret, copyright or other proprietary rights in and to such Content for publication via the Service or any other services pursuant to these Terms of Service.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.	For clarity, you retain all of your ownership rights in your Content.  However, by submitting Content to Veam, you hereby grant Veam a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the Content in connection with the Service and Veam's (and its successors' and affiliates') business, including without limitation for promoting and redistributing part or all of the Service and/or Content (and derivative works thereof) in any media formats and through any media channels.  You also hereby grant each end-user a non-exclusive, worldwide, royalty-bearing or royalty-free (as directed by you), non-sublicenseable, and non-transferable license to access your Content through the Service, and to use, reproduce (only for backup purposes), display and playback such Content as permitted through the functionality of the Service and under these Terms of Service. The above licenses granted by you in Content you submit to the Service terminate within a commercially reasonable time, as deemed by Veam, after you remove or delete your Content from the Service.  You understand and agree, however, that Veam may retain the following: (1) server copies of your Content that have been removed or deleted; and (2) a royalty-free license to display and distribute an excerpt of your Content for the purpose of advertising or promoting the Service.  The above licenses granted by you in user comments you submit are perpetual and irrevocable.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">D.	You further agree that Content you submit to the Service will not contain third-party copyrighted material or material that is subject to other third-party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant Veam all of the license rights granted herein.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">E.	You further agree that you will not submit to the Service any Content or other material that is contrary to the General Guidelines, which may be updated from time to time, or contrary to applicable local, national, and international laws and regulations.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">F.	Veam does not endorse any Content submitted to the Service by any user or other licensor, or any opinion, recommendation, or advice expressed therein, and Veam expressly disclaims any and all liability in connection with Content.  Veam does not permit copyright infringing activities and infringement of intellectual property rights on the Service, and Veam will remove all Content if properly notified that such Content infringes on another's intellectual property rights.  Veam reserves the right to remove Content without prior notice.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">7.	Payment For Provided Content </p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	Subject to the Terms of Service, Veam shall pay you, the Content Provider, a royalty in an amount equal to the royalty rate (the "Royalty Rate") multiplied by the Net Revenue received based on the Content uploaded by you using the Service (the "Royalty Amount").  The Royalty Rate shall be mutually agreed upon by the Content Provider and Veam.  Veam shall pay the Royalty Amount to the Content Provider by a mutually agreed upon date.  All amounts payable under this Section 7(A) shall be paid in U.S. dollars (unless otherwise specified) less any deduction for any required government withholding and any applicable sales taxes, use taxes, or similar taxes.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	As used herein, the term "Net Revenue", with respect to a calendar month, shall mean the net revenue received by Veam with respect to your Content, less any deduction by any third party in connection with the sale or distribution of your Content and less any refunded amount of your Content.  </p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">C.	As an example, if your Content is distributed via the Android market, the Android market typically charges thirty percent (30%) of the proceeds from the sale of the Content and forwards the remaining seventy percent (70%) of the proceeds from the sale of your Content to Veam.  Once Veam receives the seventy percent (70%) of the proceeds, Veam then calculates the Royalty Amount by multiplying the Royalty Rate on the seventy percent (70%) of the proceeds from the sale of your Content via the Android market.  The calculated Royalty Amount is then paid to you within thirty (30) days after the end of the calendar month in which Veam received the proceeds from the sale of your Content via the Android market.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">8.	Account Termination Policy</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">A.	Veam will terminate a user's access to the Service and remove the user's Content if, under appropriate circumstances, the user is determined to be an infringer.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">B.	Veam reserves the right to decide whether Content violates these Terms of Service for reasons other than copyright infringement, such as, but not limited to, pornography, obscenity, or excessive length.  Veam may at any time, without prior notice and in its sole discretion, remove such Content and/or terminate a user's account for submitting such material in violation of these Terms of Service.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">9. 	Warranty Disclaimer</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">YOU AGREE THAT YOUR USE OF THE SERVICE SHALL BE AT YOUR SOLE RISK.  THE SERVICE IS BEING PROVIDED TO YOU ON AN "AS-IS" BASIS WITHOUT ANY WARRANTY OF ANY KIND, INCLUDING ALL IMPLIED WARRANTIES AND INCLUDING WITHOUT LIMITATION ALL WARRANTIES REGARDING CONDITION, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.  TO THE FULLEST EXTENT PERMITTED BY LAW, VEAM, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICE AND YOUR USE THEREOF.  VEAM MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICE.  VEAM DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED SERVICE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND VEAM WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICE.  AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">10. 	Limitation of Liability</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">IN NO EVENT SHALL VEAM, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTIONS.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">YOU SPECIFICALLY ACKNOWLEDGE THAT VEAM SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">NEVERTHELESS, IN NO EVENT SHALL THE AGGREGATE LIABILITY TO YOU OF VEAM, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS EXCEED ONE (1) UNITED STATES DOLLAR.</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">The Service is controlled and offered by Veam from its facilities in the United States of America. Veam makes no representations that the Service is appropriate or available for use in other locations.  Those who access or use the Service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">11. 	Indemnity</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless Veam, its parent corporation, any subsidiary corporation of Veam, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Service; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third-party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that your Content or your use of the Service caused damage to a third party.  This defense and indemnification obligation will survive these Terms of Service and your use of the Service.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">12. 	Ability to Accept Terms of Service</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service.  In any case, you affirm that you are over the age of 13, as the Service is not intended for children under 13.  If you are under 13 years of age, then please do not use the Service.  There are lots of other great web sites for you.  Talk to your parents about what sites are appropriate for you.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">13. 	Assignment</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Veam without restriction.</p>
<br><br>
<p style="font-size: 1.0em;font-weight: bold;font-family: Verdana, sans-serif;">14. 	General</p>
<p style="font-size: 0.8em;font-weight: bold;font-family: Verdana, sans-serif;">You agree that: (i) the Service shall be deemed solely based in California; and (ii) the Service shall be deemed a passive website that does not give rise to personal jurisdiction over Veam, either specific or general, in jurisdictions other than California.  These Terms of Service shall be governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles.  Any claim or dispute between you and Veam that arises in whole or in part from the Service shall be decided exclusively by a court of competent jurisdiction located in Santa Clara County, California.  These Terms of Service, together with the General Guidelines any other legal notices published by Veam on the Service, shall constitute the entire agreement between you and Veam concerning the Service and Content.  If any provision of these Terms of Service is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect.  No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and Veam's failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision.  Veam reserves the right to amend these Terms of Service at any time and without notice, and it is your responsibility to review these Terms of Service for any changes.  Your use of the Service following any amendment of these Terms of Service will signify your assent to and acceptance of its revised terms.  YOU AND VEAM AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES.  OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
<?php endif?>
<br />
<br />



		</section>
	</article>
