<?php


/**
 * This class defines the structure of the 'itunes_sales' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:07 2017
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ItunesSalesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ItunesSalesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('itunes_sales');
		$this->setPhpName('ItunesSales');
		$this->setClassname('ItunesSales');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('PROVIDER', 'Provider', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PROVIDER_COUNTRY', 'ProviderCountry', 'LONGVARCHAR', true, null, null);
		$this->addColumn('SKU', 'Sku', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DEVELOPER', 'Developer', 'LONGVARCHAR', true, null, null);
		$this->addColumn('TITLE', 'Title', 'LONGVARCHAR', true, null, null);
		$this->addColumn('VERSION', 'Version', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PRODUCT_TYPE_IDENTIFIER', 'ProductTypeIdentifier', 'LONGVARCHAR', true, null, null);
		$this->addColumn('UNITS', 'Units', 'INTEGER', true, 11, 0);
		$this->addColumn('DEVELOPER_PROCEEDS', 'DeveloperProceeds', 'LONGVARCHAR', true, null, null);
		$this->addColumn('BEGIN_DATE', 'BeginDate', 'DATE', false, null, null);
		$this->addColumn('END_DATE', 'EndDate', 'DATE', false, null, null);
		$this->addColumn('CUSTOMER_CURRENCY', 'CustomerCurrency', 'LONGVARCHAR', true, null, null);
		$this->addColumn('COUNTRY_CODE', 'CountryCode', 'LONGVARCHAR', true, null, null);
		$this->addColumn('CURRENCY_OF_PROCEEDS', 'CurrencyOfProceeds', 'LONGVARCHAR', true, null, null);
		$this->addColumn('APPLE_IDENTIFIER', 'AppleIdentifier', 'LONGVARCHAR', true, null, null);
		$this->addColumn('CUSTOMER_PRICE', 'CustomerPrice', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PROMO_CODE', 'PromoCode', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PARENT_IDENTIFIER', 'ParentIdentifier', 'LONGVARCHAR', true, null, null);
		$this->addColumn('SUBSCRIPTION', 'Subscription', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PERIOD', 'Period', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DEL_FLG', 'DelFlg', 'INTEGER', true, 11, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ItunesSalesTableMap
