<?php


/**
 * This class defines the structure of the 'pdf' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:08 2017
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PdfTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PdfTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('pdf');
		$this->setPhpName('Pdf');
		$this->setClassname('Pdf');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('EXPLANATION', 'Explanation', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PDF_CATEGORY_ID', 'PdfCategoryId', 'INTEGER', true, 11, 0);
		$this->addColumn('PDF_SUB_CATEGORY_ID', 'PdfSubCategoryId', 'INTEGER', true, 11, 0);
		$this->addColumn('KIND', 'Kind', 'INTEGER', true, 11, null);
		$this->addColumn('TITLE', 'Title', 'LONGVARCHAR', true, null, null);
		$this->addColumn('THUMBNAIL_URL', 'ThumbnailUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('THUMBNAIL_SIZE', 'ThumbnailSize', 'INTEGER', true, 11, null);
		$this->addColumn('TOKEN', 'Token', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PDF_URL', 'PdfUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PDF_SIZE', 'PdfSize', 'INTEGER', true, 11, null);
		$this->addColumn('DISPLAY_ORDER', 'DisplayOrder', 'INTEGER', true, 11, 1);
		$this->addColumn('DEL_FLG', 'DelFlg', 'INTEGER', true, 11, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('APP_ID', 'AppId', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PdfTableMap
