<?php


/**
 * This class defines the structure of the 'store_subscription_receipt' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:10 2017
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StoreSubscriptionReceiptTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StoreSubscriptionReceiptTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('store_subscription_receipt');
		$this->setPhpName('StoreSubscriptionReceipt');
		$this->setClassname('StoreSubscriptionReceipt');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('USER_ID', 'UserId', 'LONGVARCHAR', true, null, null);
		$this->addColumn('QUANTITY', 'Quantity', 'INTEGER', true, 11, null);
		$this->addColumn('PRODUCT_ID', 'ProductId', 'LONGVARCHAR', true, null, null);
		$this->addColumn('TRANSACTION_ID', 'TransactionId', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PURCHASE_DATE', 'PurchaseDate', 'LONGVARCHAR', false, null, null);
		$this->addColumn('ORIGINAL_TRANSACTION_ID', 'OriginalTransactionId', 'LONGVARCHAR', true, null, null);
		$this->addColumn('ORIGINAL_PURCHASE_DATE', 'OriginalPurchaseDate', 'LONGVARCHAR', false, null, null);
		$this->addColumn('APP_ITEM_ID', 'AppItemId', 'LONGVARCHAR', true, null, null);
		$this->addColumn('VERSION_EXTERNAL_IDENTIFIER', 'VersionExternalIdentifier', 'LONGVARCHAR', true, null, null);
		$this->addColumn('BID', 'Bid', 'LONGVARCHAR', true, null, null);
		$this->addColumn('BVRS', 'Bvrs', 'LONGVARCHAR', true, null, null);
		$this->addColumn('EXPIRES_DATE', 'ExpiresDate', 'LONGVARCHAR', true, null, null);
		$this->addColumn('LATEST_RECEIPT', 'LatestReceipt', 'LONGVARCHAR', true, null, null);
		$this->addColumn('LATEST_RECEIPT_INFO', 'LatestReceiptInfo', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DEL_FLG', 'DelFlg', 'INTEGER', true, 11, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // StoreSubscriptionReceiptTableMap
