<?php


/**
 * This class defines the structure of the 'youtube_video' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec 13 16:31:12 2017
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class YoutubeVideoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.YoutubeVideoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('youtube_video');
		$this->setPhpName('YoutubeVideo');
		$this->setClassname('YoutubeVideo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('APP_ID', 'AppId', 'INTEGER', true, 11, null);
		$this->addColumn('KIND', 'Kind', 'INTEGER', true, 11, 1);
		$this->addColumn('RATING', 'Rating', 'INTEGER', true, 11, null);
		$this->addColumn('AUTHOR', 'Author', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DURATION', 'Duration', 'INTEGER', true, 11, null);
		$this->addColumn('EXPIRED_AT', 'ExpiredAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TITLE', 'Title', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', true, null, null);
		$this->addColumn('CATEGORY_ID', 'CategoryId', 'INTEGER', true, 11, null);
		$this->addColumn('SUB_CATEGORY_ID', 'SubCategoryId', 'INTEGER', true, 11, null);
		$this->addColumn('YOUTUBE_CODE', 'YoutubeCode', 'LONGVARCHAR', true, null, null);
		$this->addColumn('IS_NEW', 'IsNew', 'INTEGER', true, 11, 0);
		$this->addColumn('DOWNLOADABLE', 'Downloadable', 'INTEGER', true, 11, null);
		$this->addColumn('SMALL_THUMBNAIL_URL', 'SmallThumbnailUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('LARGE_THUMBNAIL_URL', 'LargeThumbnailUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('VIDEO_URL', 'VideoUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('VIDEO_SIZE', 'VideoSize', 'INTEGER', true, 11, null);
		$this->addColumn('VIDEO_KEY', 'VideoKey', 'LONGVARCHAR', true, null, null);
		$this->addColumn('PRICE', 'Price', 'INTEGER', true, 11, null);
		$this->addColumn('LINK_URL', 'LinkUrl', 'LONGVARCHAR', true, null, null);
		$this->addColumn('DISPLAY_ORDER', 'DisplayOrder', 'INTEGER', true, 11, 1);
		$this->addColumn('DEL_FLG', 'DelFlg', 'INTEGER', true, 11, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // YoutubeVideoTableMap
