generator:
  class: sfPropelGenerator
  param:
    model_class:           Textline
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Textline
    plural:                Textlines
    route_prefix:          textline_c_text
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: { date_format: yyyy/MM/dd HH:mm:ss }
      list:
        title: Text List
        display: [title,textline_category_name, created_at, type]
        peer_method: doSelectWithGroup
        peer_count_method: doCountWithGroup
        batch_actions: {}
      filter:
        class: false
      form: ~
#        display:
#          Text: [title, sub_title,text]
      edit:
        title: Edit Text
      new:
        title: New Text
